export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
  },
  properties: {
    list: '/listings',
    mine: '/listings/owner/me',
    search: '/listings/search',
    byId: (id: number | string) => `/listings/${id}`,
  },
  bookings: {
    listMine: '/bookings/me',
    listOwner: '/bookings/owner',
    create: '/bookings',
    unavailableDates: (listingId: number | string) => `/bookings/listing/${listingId}/unavailable-dates`,
    updateStatus: (id: number | string) => `/bookings/${id}/status`,
    verifyCheckIn: (id: number | string) => `/bookings/${id}/verify-checkin`,
    delete: (id: number | string) => `/bookings/${id}`,
  },
  payments: {
    checkout: (bookingId: number | string) => `/payments/checkout/${bookingId}`,
  },
  reviews: {
    create: '/reviews',
    listByProperty: (propertyId: number | string) => `/reviews/listing/${propertyId}`,
    canReview: (propertyId: number | string) => `/reviews/can-review/${propertyId}`,
  },
  messages: {
    send: '/messages',
    inbox: '/messages/inbox',
    outbox: '/messages/sent',
    conversations: '/messages/conversations',
    conversation: (userId: number | string) => `/messages/conversations/${userId}`,
  },
  users: {
    me: '/users/me',
    updateMe: '/users/me',
    search: (query: string) => `/users/search?q=${encodeURIComponent(query)}`,
  },
  wishlist: {
    list: '/wishlist',
    add: (listingId: number | string) => `/wishlist/${listingId}`,
    remove: (listingId: number | string) => `/wishlist/${listingId}`,
  },
  dashboard: {
    tenantSummary: '/dashboard/tenant/summary',
    hostSummary: '/dashboard/host/summary',
    adminSummary: '/dashboard/admin/summary',
  },
  admin: {
    users: '/admin/users',
    userOverview: (userId: number | string) => `/admin/users/${userId}/overview`,
    userHistory: (userId: number | string) => `/admin/users/${userId}/history`,
    userMessages: (userId: number | string) => `/admin/users/${userId}/messages`,
    userListings: (userId: number | string) => `/admin/users/${userId}/listings`,
    userBookings: (userId: number | string) => `/admin/users/${userId}/bookings`,
    userEarnings: (userId: number | string) => `/admin/users/${userId}/earnings`,
    userPermissions: (userId: number | string) => `/admin/users/${userId}/permissions`,
    approveGuestVerification: (userId: number | string) => `/admin/guest-verifications/${userId}/approve`,
    rejectGuestVerification: (userId: number | string) => `/admin/guest-verifications/${userId}/reject`,
    updateUser: (userId: number | string) => `/admin/users/${userId}`,
    updateUserPassword: (userId: number | string) => `/admin/users/${userId}/password`,
    deleteUser: (userId: number | string) => `/admin/users/${userId}`,
    blockUser: (id: number | string) => `/admin/users/${id}/block`,
    bookings: '/admin/bookings',
    pendingListings: '/admin/pending-listings',
    verifyProperty: (id: number | string) => `/admin/properties/${id}/verify`,
    growthMetrics: '/admin/growth-metrics',
    hostDemands: '/admin/host-demands',
    hostDemandById: (id: number | string) => `/admin/host-demands/${id}`,
    approveHostDemand: (id: number | string) => `/admin/host-demands/${id}/approve`,
    rejectHostDemand: (id: number | string) => `/admin/host-demands/${id}/reject`,
  },
  connections: {
    list: '/connections',
    pending: '/connections/pending',
    request: '/connections/request',
    accept: (id: number | string) => `/connections/${id}/accept`,
  },
  verifications: {
    guestStatus: '/verifications/guest/status',
    sendEmailOtp: '/verifications/guest/email/send-otp',
    verifyEmailOtp: '/verifications/guest/email/verify-otp',
    sendPhoneOtp: '/verifications/guest/phone/send-otp',
    verifyPhoneOtp: '/verifications/guest/phone/verify-otp',
    submitIdentity: '/verifications/guest/identity',
  },
} as const
