# MongoDB configuration (MongoDB Compass)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/rental_platform}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:rental_platform}

# JWT settings
jwt.secret=${JWT_SECRET:bXktc3Ryb25nLXN1cGVyLXNlY3JldC1rZXktMzItYnl0ZXM=}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# CORS
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}

# Server settings
server.port=${SERVER_PORT:8081}

# Multipart upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Mocean Verify configuration
mocean.api.key=${MOCEAN_API_KEY:oussama1809}
mocean.api.secret=${MOCEAN_API_SECRET:apit-lpwTrVlfdZ2V6Y5CRsjjBTMpiS05Wth5-GBOWk}
mocean.api.token=${MOCEAN_API_TOKEN:apit-lpwTrVlfdZ2V6Y5CRsjjBTMpiS05Wth5-GBOWk}
mocean.verify.brand=${MOCEAN_VERIFY_BRAND:Maskan}

# Email SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=balti.oussama.business@gmail.com
spring.mail.password=bmmbvqwxrxsibkmc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
